version: '3.8'
services:

  postgres:
    image: postgres
    container_name: postgres_container
    hostname: postgresDb
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  
  mongo:
    image: mongo
    container_name: mongo_container
    hostname: mongodb
    ports:
      - "27017:27017"

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq_container
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    ports:
      - "5672:5672"
      - "15672:15672"